apiVersion: batch/v1
kind: Job
metadata:
  name: test-deploy-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - sh
            - -c
            - |
              sleep 5
              echo "deploy-job"
