apiVersion: batch/v1
kind: Job
metadata:
  name: test-pre-deploy-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - sh
            - -c
            - |
              sleep 10
              echo "new pre-deploy job"
