apiVersion: batch/v1
kind: Job
metadata:
  name: test-db-migration-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - sh
            - -c
            - echo "pre-deploy-job"
