apiVersion: batch/v1
kind: Job
metadata:
  name: test-db-migration-job-new
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Running migration job"
              sleep 5
              echo "Migration job completed"
