apiVersion: batch/v1
kind: Job
metadata:
  name: test-health-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - sh
            - -c
            - echo "health-job"
